### ISSUE TITLE
Cannot Exclude Rules 

### ISSUE THREAD

**Issue by brodkin** [gskema/phpcs-type-sniff#20]
As a developer I do not want to require return types to be declared for test methods since all test methods always return void and this does not add value.

I expect to be able to use the standard exclude syntax to exclude the sniffs for my ruleset in one of the following formats:

**Syntax #1**
```
<rule ref="Gskema.Sniffs.CompositeCodeElement.FqcnMethodSniff">
    <exclude-pattern>*/tests/*</exclude-pattern>
</rule>
```

The above syntax causes an error to be thrown:
```
ERROR: Referenced sniff "Gskema.Sniffs.CompositeCodeElement.FqcnMethodSniff" does not exist
```

**Syntax #2**
```
<rule ref="./vendor/gskema/phpcs-type-sniff/src/Sniffs/CompositeCodeElementSniff.php">
    <exclude-pattern>*/tests/*</exclude-pattern>
</rule>
```
The above syntax causes the exclude-pattern key to be ignored entirely.

Expected behavior is that the sniffs are not applied at the specified path.

**Comment by brodkin** [comment]
P.S. I'm not 100% sure that this is an issue with this project's implementation. It could easily be my implementation or a limitation of PHPCS.

**Comment by gskema** [comment]
Hi. at the moment there are no plans to implement this. Syntax 1 doesn't work because it's a custom "sub-sniff" class, file path matching needs to implemented again, even though phpcs already does it for "whole" sniffs - e.g. Syntax 2 should work.
Also I know I shouldn't be questioning how people will use a feature/configuration, but I don't agree with your phpunit example.

**Comment by brodkin** [comment]
No offense taken to the disagreement. :)

Thanks for the reply!
